name: deno-deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - run: yarn
      - run: yarn build
        env:
          NITRO_PRESET: deno_deploy
      - name: weixin-wenzhang-daochu
        uses: denoland/deployctl@v1
        with:
          project: wedown12345691232323123-23
          entrypoint: server/index.ts
          root: .output
